# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 53310:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
