# Use root/example as user/password credentials
version: "3.1"

services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 53310:3306
    volumes:
      - db-data-mysql:/var/lib/mysql
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 53312:5432
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
volumes:
  db-data-mysql:
    driver: local
  db-data-postgres:
    driver: local
